// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/how-it-works": {
    params: {};
  };
  "/economy": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/agents": {
    params: {};
  };
  "/dashboard/transactions": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/how-it-works" | "/economy" | "/dashboard" | "/dashboard/agents" | "/dashboard/transactions" | "/dashboard/settings" | "/about";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/how-it-works.tsx": {
    id: "routes/how-it-works";
    page: "/how-it-works";
  };
  "routes/economy.tsx": {
    id: "routes/economy";
    page: "/economy";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/agents" | "/dashboard/transactions" | "/dashboard/settings";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.agents.tsx": {
    id: "routes/dashboard.agents";
    page: "/dashboard/agents";
  };
  "routes/dashboard.transactions.tsx": {
    id: "routes/dashboard.transactions";
    page: "/dashboard/transactions";
  };
  "routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/dashboard/settings";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/how-it-works": typeof import("./app/routes/how-it-works.tsx");
  "routes/economy": typeof import("./app/routes/economy.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/dashboard.agents": typeof import("./app/routes/dashboard.agents.tsx");
  "routes/dashboard.transactions": typeof import("./app/routes/dashboard.transactions.tsx");
  "routes/dashboard.settings": typeof import("./app/routes/dashboard.settings.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
};